language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: ln6cBoGk/8CR0Cj1SbpA8vr2Fk1qmfq1Bplo1CY6xgOihBjqkeQMr2HnZ7cxQaGaWwqaO+mEJsZJJcqE59m/uwvsQrmq7dLrl45ML1VXGbFW+odGqpjwf0rzYHwvvM2/anRQHGf9n2dY11JjwAESRFimbw1szaFKSnntlg4aD6W86L7K3SnGbKiv757EfDv29BwIOR5MU6w4A9m+rioXTX8jd7cgNfH7/tYP+htdCvIywNwOxhoq8rXBEbNTesgywYtY5tdYMnHmPFsst6TAxTAFmXQeVEmEoM24652wMlJDYqjknEROg49wkC/hw5St/QcaXRsJyMlVkkXxkeTnzVOAaSENvg+Q400T/RLOrXAtarNemhQ8yf9RwSrF5QXthTBkC0z44tUF237b0JjxO0Es4fAcdx2Y0XZp/cNHYNE09lK1q/27r5JDc6Sk3GX/Ypb6PwAx33DNK1VO2RRP+T/YIgYPG2DFfjztDNzo6rjz5+rLVtR3ExlC82yrEWAptpKReV1tJUIolAAb85lG8sBWt4jLdxnrF0XtZarFwy9VrG17i2hRVqJudN+RpcwyR4DCiKZi4c0OtCojVpLIDDL4a6gyAFvNId0cYKM2g1haWYPlidvrt6tCfAGedSBQJ3OsOot5NAz0avV5HISXdpg3APP9YvrLLGHh1hPcexw=
  app: lafka-2016
  on:
    repo: mlampola/lafka
